FROM alpine
RUN apk update
RUN apk add openjdk8
RUN apk add maven 
WORKDIR /root/App42PaaS
ADD . /root/App42PaaS
RUN mvn package
RUN mkdir data && cp target/*.war data/ && cp Config.properties data/Config.properties
