version: '3.7'

services:

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: base
    volumes:
      - type: volume
        source: db 
        target: /var/lib/mysql

  building:
    build:
      dockerfile: Dockerfile_build
      context: .
    volumes:
      - type: volume
        source: vol1
        target: /root/App42PaaS/data

  prod:
   depends_on:  
     - database
     - building
   build: pr
   ports:
      - "8081:8080"
   volumes:
     - type: volume
       source: vol1
       target: /usr/local/tomcat/webapps

volumes:
  db:
  vol1:
