version: '3.7'

services:

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: base
    volumes:
      - db:/var/lib/mysql

  building:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile_build
      context: .
    volumes:
          - vol_b:/tmp/App42PaaS


  prod:
   depends_on:  
     - database
     - building
   build:
     dockerfile: Dockerfile_build
     context: .
   ports:
      - '8081:8080'
   volumes:
      - vol_b:/build  




volumes:
  db:
  vol_b:
