FROM tomcat
WORKDIR /usr/local/tomcat/
RUN mkdir /usr/local/tomcat/webapps/ROOT
EXPOSE 8080
RUN cp /tmp/target/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT.war webapps/ && cp /build/Config.properties webapps/ROOT/ 
CMD ["catalina.sh", "run"]
